### ISSUE TITLE
Torwart-Häkchen im Kader, damit diese in der Tabelle VOR dem Rest der MAnnschaft stehen

### ISSUE THREAD

**Issue by razerboellee** [berryelectronics/WIP#12]
Die Möglichkeit einen HAken im Kader zu setzen, damit der Rechner weiß, wer Torwart ist. Die Spieler bitte nach Nummer sortieren - Erst Torwart in Chronologie - dann der Rest des Teams.

**Comment by berryelectronics** [comment]
Also jetzt können die Position der Spieler festgelegt werden, damit sollte es klappen. 
Soll der Torwart dann irgendwie gekennzeichnet werden?
